name: Update docs
on:
  push:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  update-docs:
    name: Update docs
    uses: unifyai/workflows/.github/workflows/docs.yml@main
    secrets: inherit
    with:
      repo-name: hub